version: '3.9'

services:
  db:
    image: postgres:alpine
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - internal
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=nextcloud

  nextcloud:
    image: nextcloud:apache
    restart: always
    ports:
      - "8086:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - nextcloud:/var/www/html
      - ${APP_DIR:-./../../custom_apps}:/var/www/html/custom_apps
    networks:
      - internal
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=nextcloud
    depends_on:
      - db

  cron:
    image: nextcloud:apache
    restart: always
    volumes:
      - nextcloud:/var/www/html
    networks:
      - internal
    entrypoint: /cron.sh
    depends_on:
      - db

volumes:
  db:
  nextcloud:

networks:
  internal:
